// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDe_DmJBD4aFBOrUlLrJBB5Snoc1yPBljE', // fieldmanager 키
  appId: '1:1023081610040:web:0ff5070edd63eca65fdfcd',
  messagingSenderId: '1023081610040',
  projectId: 'fieldmanager-c94c2', // 👈 여기가 핵심입니다!
  authDomain: 'fieldmanager-c94c2.firebaseapp.com',
  storageBucket: 'fieldmanager-c94c2.firebasestorage.app',
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9W7f3_MOkGXOzgw4OGEnNMy1yM8VSPw',
    appId: '1:1023081610040:android:24a1db52dfb740965fdfcd',
    messagingSenderId: '1023081610040',
    projectId: 'fieldmanager-c94c2',
    storageBucket: 'fieldmanager-c94c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6b7hX5bapEOkMRVHw8DZxe1UFAuOVpk',
    appId: '1:1023081610040:ios:9b74b6ef95f8f8ca5fdfcd',
    messagingSenderId: '1023081610040',
    projectId: 'fieldmanager-c94c2',
    storageBucket: 'fieldmanager-c94c2.firebasestorage.app',
    iosBundleId: 'com.example.fieldManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6b7hX5bapEOkMRVHw8DZxe1UFAuOVpk',
    appId: '1:1023081610040:ios:9b74b6ef95f8f8ca5fdfcd',
    messagingSenderId: '1023081610040',
    projectId: 'fieldmanager-c94c2',
    storageBucket: 'fieldmanager-c94c2.firebasestorage.app',
    iosBundleId: 'com.example.fieldManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe_DmJBD4aFBOrUlLrJBB5Snoc1yPBljE',
    appId: '1:1023081610040:web:de1e34a1d490e6575fdfcd',
    messagingSenderId: '1023081610040',
    projectId: 'fieldmanager-c94c2',
    authDomain: 'fieldmanager-c94c2.firebaseapp.com',
    storageBucket: 'fieldmanager-c94c2.firebasestorage.app',
    measurementId: 'G-T1FCEDHDJ0',
  );
}
